title: GlobalSphere Almanac
description: Wiki for the GlobalSphere Minecraft server
theme: yellow_old_style

url: https://globalspheremc.github.io

nav_external_links:
  - title: Discord
    url: https://discord.gg/RnVwUZmMY3
    hide_icon: false
  - title: Server Map
    url: http://globalmap.ddns.net/
    hide_icon: false
